# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cy', '0002_auto_20170331_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cy.Category', verbose_name='\u7236\u7ea7\u5206\u7c7b'),
        ),
    ]
