# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 02:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cy', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u6b63\u6587')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cy.Person', verbose_name='\u4f5c\u8005')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cy.Category', verbose_name='\u5206\u7c7b')),
            ],
        ),
        migrations.AlterField(
            model_name='cy',
            name='derivation',
            field=models.TextField(blank=True, max_length=1024, verbose_name='\u51fa\u5904'),
        ),
    ]
