# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 07:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cy', '0005_auto_20170331_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellCome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellcome', ckeditor.fields.RichTextField(verbose_name='\u6b22\u8fce\u8bed')),
                ('shell', models.CharField(max_length=32, verbose_name='\u7b49\u5f85\u8f93\u5165')),
            ],
            options={
                'verbose_name': '\u6b22\u8fce\u8bed',
                'verbose_name_plural': '\u6b22\u8fce\u8bed',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u535a\u6587', 'verbose_name_plural': '\u535a\u6587'},
        ),
    ]
