# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cy', '0006_auto_20170331_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellcome',
            name='title',
            field=models.CharField(max_length=32, null=True, verbose_name='\u7f51\u7ad9\u6807\u9898'),
        ),
    ]
