# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cy', '0007_wellcome_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WellCome',
            new_name='Welcome',
        ),
        migrations.RenameField(
            model_name='welcome',
            old_name='wellcome',
            new_name='welcome',
        ),
    ]
