# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cy', '0008_auto_20170331_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='\u547d\u4ee4\u540d')),
                ('description', models.CharField(max_length=128, verbose_name='\u8bf4\u660e')),
                ('order', models.IntegerField(verbose_name='\u987a\u5e8f')),
            ],
            options={
                'verbose_name': '\u5e2e\u52a9',
                'verbose_name_plural': '\u547d\u4ee4\u8bf4\u660e',
            },
        ),
    ]
