# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cy', '0009_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='order',
        ),
    ]
