# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cy', '0013_auto_20170401_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name': '\u914d\u7f6e', 'verbose_name_plural': '\u914d\u7f6e'},
        ),
        migrations.AddField(
            model_name='article',
            name='display',
            field=models.BooleanField(default=True, verbose_name='\u5c55\u793a'),
        ),
        migrations.AlterField(
            model_name='help',
            name='display',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u5c55\u793a'),
        ),
    ]
